language: node_js
node_js:
  - '14'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - cd backend
  - Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  - choco install -y python2 gtk-runtime microsoft-build-tools libjpeg-turbo
  - npm update
install:
  - npm install
script:
  - npm test
