language: node_js
node_js:
  - lts/*
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - cd backend
  - npm update
install:
  - npm install
script:
  - npm test
