language: node_js
node_js:
  - lts/*
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - cd backend
  - sudo apt-get install ca-certificates && \
    wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk && \
    sudo apt-get install glibc-2.29-r0.apk && \
    npm install canvas@2.6.1
install:
  - npm install
script:
  - npm test
