os: windows
language: node_js
node_js:
  - '14'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - cd backend
  - choco install -y python2 gtk-runtime microsoft-build-tools libjpeg-turbo
  - npm update
install:
  - npm install
script:
  - npm test
